export interface UserSeed {
  username: string;
  displayName: string;
  email: string;
  trustTier: "new" | "established" | "trusted" | "moderator" | "admin";
  reputationScore: number;
  persuasionRating: number;
  createdAt: Date;
}

export const USER_SEEDS: UserSeed[] = [
  // ─── Admin (1) ────────────────────────────────────────────
  {
    username: "marcus_reformed",
    displayName: "Marcus Whitfield",
    email: "marcus.whitfield@christiandebate.org",
    trustTier: "admin",
    reputationScore: 4850,
    persuasionRating: 1720,
    createdAt: new Date("2025-03-01T10:00:00Z"),
  },

  // ─── Moderators (2) ──────────────────────────────────────
  {
    username: "sister_catherine",
    displayName: "Catherine Delacroix",
    email: "c.delacroix@stbenedicts.edu",
    trustTier: "moderator",
    reputationScore: 3920,
    persuasionRating: 1580,
    createdAt: new Date("2025-04-08T14:30:00Z"),
  },
  {
    username: "pastor_james",
    displayName: "James Okonkwo",
    email: "james.okonkwo@gracechapel.org",
    trustTier: "moderator",
    reputationScore: 3640,
    persuasionRating: 1490,
    createdAt: new Date("2025-05-12T09:15:00Z"),
  },

  // ─── Trusted (4) ─────────────────────────────────────────
  {
    username: "dr_philosophy",
    displayName: "Dr. Eleanor Hartwell",
    email: "ehartwell@westminster-seminary.edu",
    trustTier: "trusted",
    reputationScore: 3100,
    persuasionRating: 1450,
    createdAt: new Date("2025-04-15T11:00:00Z"),
  },
  {
    username: "orthodox_david",
    displayName: "David Konstantinos",
    email: "d.konstantinos@orthodox-forum.net",
    trustTier: "trusted",
    reputationScore: 2870,
    persuasionRating: 1380,
    createdAt: new Date("2025-05-03T16:45:00Z"),
  },
  {
    username: "historian_ruth",
    displayName: "Ruth Abernathy",
    email: "rabernathy@divinity.duke.edu",
    trustTier: "trusted",
    reputationScore: 2950,
    persuasionRating: 1410,
    createdAt: new Date("2025-05-22T08:30:00Z"),
  },
  {
    username: "chaplain_mike",
    displayName: "Lt. Col. Michael Torres",
    email: "michael.torres@mil-chaplains.org",
    trustTier: "trusted",
    reputationScore: 2680,
    persuasionRating: 1340,
    createdAt: new Date("2025-06-10T13:20:00Z"),
  },

  // ─── Established (8) ─────────────────────────────────────
  {
    username: "sola_gratia",
    displayName: "Jonathan Mercer",
    email: "jmercer@reformedfaith.com",
    trustTier: "established",
    reputationScore: 2100,
    persuasionRating: 1260,
    createdAt: new Date("2025-06-18T10:00:00Z"),
  },
  {
    username: "campus_grace",
    displayName: "Priya Mathews",
    email: "priya.mathews@intervarsity.org",
    trustTier: "established",
    reputationScore: 1940,
    persuasionRating: 1210,
    createdAt: new Date("2025-07-05T15:30:00Z"),
  },
  {
    username: "youthpastor_dev",
    displayName: "Devon Richards",
    email: "devon@crossroadyouth.church",
    trustTier: "established",
    reputationScore: 1780,
    persuasionRating: 1180,
    createdAt: new Date("2025-07-20T09:45:00Z"),
  },
  {
    username: "liberation_theo",
    displayName: "Rev. Maria Santos",
    email: "msantos@liberation-theology.org",
    trustTier: "established",
    reputationScore: 2050,
    persuasionRating: 1240,
    createdAt: new Date("2025-08-01T12:00:00Z"),
  },
  {
    username: "pentecostal_fire",
    displayName: "Blessing Adeyemi",
    email: "blessing@holyghostfire.church",
    trustTier: "established",
    reputationScore: 1650,
    persuasionRating: 1150,
    createdAt: new Date("2025-08-14T17:30:00Z"),
  },
  {
    username: "anabaptist_peace",
    displayName: "Hannah Yoder",
    email: "hyoder@mennonite-witness.org",
    trustTier: "established",
    reputationScore: 1890,
    persuasionRating: 1200,
    createdAt: new Date("2025-09-02T08:15:00Z"),
  },
  {
    username: "christian_lawyer",
    displayName: "Robert Chen",
    email: "rchen@faithandjustice.law",
    trustTier: "established",
    reputationScore: 1720,
    persuasionRating: 1170,
    createdAt: new Date("2025-09-15T14:00:00Z"),
  },
  {
    username: "worship_leader_k",
    displayName: "Keisha Washington",
    email: "keisha@newsongrising.com",
    trustTier: "established",
    reputationScore: 1560,
    persuasionRating: 1130,
    createdAt: new Date("2025-09-28T11:30:00Z"),
  },

  // ─── New (10) ─────────────────────────────────────────────
  {
    username: "messianic_ari",
    displayName: "Ari Goldstein",
    email: "ari@bethyeshua.org",
    trustTier: "new",
    reputationScore: 420,
    persuasionRating: 1050,
    createdAt: new Date("2025-10-10T10:00:00Z"),
  },
  {
    username: "medical_ethicist",
    displayName: "Dr. Sarah Kim",
    email: "skim@bioethics-faith.org",
    trustTier: "new",
    reputationScore: 380,
    persuasionRating: 1040,
    createdAt: new Date("2025-10-25T16:00:00Z"),
  },
  {
    username: "progressive_chris",
    displayName: "Taylor Morrison",
    email: "taylor@progressivefaith.blog",
    trustTier: "new",
    reputationScore: 510,
    persuasionRating: 1060,
    createdAt: new Date("2025-11-05T13:45:00Z"),
  },
  {
    username: "seminary_student",
    displayName: "Luke Andersen",
    email: "landersen@fuller.edu",
    trustTier: "new",
    reputationScore: 290,
    persuasionRating: 1020,
    createdAt: new Date("2025-11-18T09:30:00Z"),
  },
  {
    username: "missionary_heart",
    displayName: "Grace Nakamura",
    email: "grace@omfmissions.org",
    trustTier: "new",
    reputationScore: 340,
    persuasionRating: 1030,
    createdAt: new Date("2025-12-01T08:00:00Z"),
  },
  {
    username: "homeschool_mom",
    displayName: "Rebecca Patterson",
    email: "rebecca@faithfulfamilies.net",
    trustTier: "new",
    reputationScore: 260,
    persuasionRating: 1015,
    createdAt: new Date("2025-12-15T14:30:00Z"),
  },
  {
    username: "ex_pastor_scholar",
    displayName: "Daniel Reeves",
    email: "dreeves@religious-studies.yale.edu",
    trustTier: "new",
    reputationScore: 480,
    persuasionRating: 1055,
    createdAt: new Date("2026-01-08T11:00:00Z"),
  },
  {
    username: "anglican_vicar",
    displayName: "Rev. Thomas Weatherby",
    email: "tweatherby@anglicancommunion.org",
    trustTier: "new",
    reputationScore: 350,
    persuasionRating: 1035,
    createdAt: new Date("2026-01-22T10:15:00Z"),
  },
  {
    username: "respectful_skeptic",
    displayName: "Sam Nguyen",
    email: "snguyen@honest-questions.com",
    trustTier: "new",
    reputationScore: 190,
    persuasionRating: 1010,
    createdAt: new Date("2026-02-05T15:45:00Z"),
  },
  {
    username: "christian_scientist",
    displayName: "Dr. Benjamin Okafor",
    email: "bokafor@faith-and-science.org",
    trustTier: "new",
    reputationScore: 310,
    persuasionRating: 1025,
    createdAt: new Date("2026-02-20T12:30:00Z"),
  },
];
